var langArr = {
    "zh": {
        "header_1": "註冊",
        "header_2": "<img src='img/lang.png'/>繁體中文",
        "header_3": "English",
        "header_4": "Tiếng Việt",
        "header_5": "ไทย",
        "header_6": "繁體中文",
        "section28_1": "您需要的槓桿交易策略<p>就在這裡！</p>",
        "section28_2": "金融市場瞬息萬變，如何才能巧妙運用槓桿交易取得勝利？",
        "section28_3": "怎樣才能找出槓桿支點的位置去撬動整個市場？",
        "section28_4": "開設模擬賬戶",
        "section28_5": "+886",
        "section28_6": "台灣 <span>+886</span>",
        "section28_7": "越南 <span>+84</span>",
        "section28_8": "泰國 <span>+66</span>",
        "section28_9": "韓國 <span>+82</span>",
        "section28_10": "菲律賓 <span>+63</span>",
        "section28_11": "馬來西亞 <span>+60</span>",
        "section28_12": "中國 <span>+86</span>",
        "section28_13": "澳大利亞 <span>+61</span>",
        "section28_14": "獲取驗證碼",
        "section28_15": "安全註冊",
        "section28_16": "更多登錄方式",
        "section28_17": "已有賬戶？<a class='account-href' style='color:#0047BB;font-weight: 500;'>登錄</a>",
        "section31_1": "槓桿交易到底是怎樣一回事？",
        "section31_2": "槓桿交易，顧名思義，就是利用小額的資金來進行數倍於原始金額的交易。",
        "section31_3": "交易者只需利用槓桿，即可全面增大購買力，發揮無限交易潛能！",
        "section31_4": "請注意，槓桿也會放大您的損失。",
        "section31_5": "槓桿交易有甚麼特點？",
        "section31_6": "槓桿操作有放大效果，交易者能以小博大",
        "section31_7": "交易者可隨時選擇做多或做空",
        "section31_8": "只需利用市場波動，即可輕鬆捕獲更多交易良機",
        "section31_9": "利用杠杆交易心仪市场",
        "section31_10": "槓桿操作有放大效果，交易者能以小博大",
        "section31_11": "交易者可隨時選擇做多或做空",
        "section31_12": "只需利用市場波動，即可輕鬆捕獲更多交易良機",
        "section31_13": "隨時隨地掌握市場",
        "section31_14": "簡單數步 即可開戶",
        "section31_15": "1.註冊真實賬戶",
        "section31_16": "只需利用電郵地址/手機號碼，配以登入密碼，即可開戶",
        "section31_17": "2.賬戶注資",
        "section31_18": "Mitrade提供不同類型的入金方式，包括︰電匯、Visa/Mastercard及電子錢包等^",
        "section31_19": "3.檢查賬戶，開始交易",
        "section31_20": "提供快速而高效的入金服務，您的资金将立即存入您的账户。存款之前，請確保您已開通國際付款功能。",
        "section31_21": "4.一邊交易，一邊獲取獎賞",
        "section31_22": "通過參加我們的贈金計劃，獲取高達 $3,000* 的交易獎勵",
        "section31_23": "立即開始交易",
        "section31_24": "^並非所有方法都適用於您所在的國家/地區，請參閱我們的平台以獲取詳細信息",
        "section31_25": "為甚麼要選擇 Mitrade？",
        "section31_26": "受ASIC嚴格規管",
        "section31_27": "0佣金、低成本交易",
        "section31_28": "高達1:200的槓桿及低價差",
        "section31_29": "Trading Central獨家市場分析",
        "section31_30": "免費熱門交易",
        "section31_31": "一週5天24小時客戶服務",
        "section31_32": "平台擁有網頁版及手機APP",
        "section31_33": "快速出入金服務",
        "section31_34": "立即參加我們的獨家獎賞計劃！",
        "section31_35": "開設真實賬戶時可享$50*的交易體驗金（名額有限)<br>交易達標時可領取高達$3,000*的贈金<br>交易越多，贈金越高！",
        "section31_36": "立即開始交易",
        "section31_37": "*條款和條件適用，請查看我們的網站以獲取詳細信息。",
        "footer_1": "欢迎体验Mitrade服务",
        "footer_2": "<img src='img/btn-icon2.png' />立即开户交易",
        "footer_3": "私隱條款 | ",
        "footer_4": "產品披露聲明 | ",
        "footer_5": "投訴政策 | ",
        "footer_6": "風險披露聲明 | ",
        "footer_7": "客戶協議 |",
        "footer_8": "金融服務指南 | ",
        "footer_9": "交易對手方對沖政策",
        "footer_10": "風險警告：交易場外衍生產品是有風險的。 它並不適合每個人，並且可能導致您損失全部投資資金。敬請在使用我們的服務前仔細閱讀產品披露聲明（PDS）、金融服務指南（FSG）、風險披露聲明和客戶協議，並確保在交易前充分了解所涉及的風險。您並不實際擁有或持有任何相關基礎資產。",
        "footer_11": "Mitrade 不提供任何關於購買、持有或出售我們產品的建議、推薦或意見。本網站上的信息屬於一般性質，不考慮您的個人目標，財務狀況或需求。請尋求您自己的獨立建議。",
        "footer_12": "我們提供的所有產品都是以全球資產作為基礎的場外衍生品。Mitrade 提供的所有服務僅基於執行交易指令。",
        "footer_13": "Mitrade Global Pty Ltd 擁有本網站的所有權和使用權。Mitrade Global Pty Ltd 由澳大利亞證券和投資委員會（Australian Securities and Investment Commission）授權及監管。",
        "footer_14": "本網站資訊不針對美國，加拿大，日本，新西蘭的居民；本網站資訊也不適合由於其發布或使用而違反當地法律或法規的任何國家或司法管轄區的任何人使用。",
        "footer_15": "對於特定區域，銀行卡服務由 Mitrade Services Ltd 提供（公司於英格蘭及威爾士註冊，註冊編號為11804044，註冊地址27 Old Gloucester Street, London, WC1N 3AX, United Kingdom）。Mitrade Services Ltd 屬 Mitrade Global Pty Ltd 之全資子公司。",
        "footer_16": "<span class='glyphicon glyphicon-lock' aria-hidden='true'></span>&nbsp;SSL 安全通訊加密。© Mitrade版權所有， 保留一切權利。| ABN 90 149 011 361 | AFSL 398528.",
        "footer_17": "",
        "footer_18": "",
        "placeholder_1": "請輸入您的訊息驗證碼",
        "placeholder_2": "請輸入密碼"
    },
    "en": {
        "header_1": "Sign in",
        "header_2": "<img src='img/lang.png'/>English",
        "header_3": "English",
        "header_4": "Tiếng Việt",
        "header_5": "ไทย",
        "header_6": "繁體中文",
        "section28_1": "The Leverage Trading Strategies You’ll Need",
        "section28_2": "The market changes by the second. How can we make use of leverage to achieve more in the financial world?",
        "section28_3": "Is there a way to find the perfect point of leverage to move the market?",
        "section28_4": "Open Live Account",
        "section28_5": "+61",
        "section28_6": "Taiwan <span>+886</span>",
        "section28_7": "Vietnam <span>+84</span>",
        "section28_8": "Thailand <span>+66</span>",
        "section28_9": "Korea <span>+82</span>",
        "section28_10": "Philippines <span>+63</span>",
        "section28_11": "Malaysia <span>+60</span>",
        "section28_12": "China <span>+86</span>",
        "section28_13": "Australia <span>+61</span>",
        "section28_14": "Get Code",
        "section28_15": "Create Account",
        "section28_16": "Or sign in with",
        "section28_17": "Already have an account? <a class='account-href' style='color:#0047BB;font-weight: 500;'>Log in</a>",
        "section31_1": "Trading with Leverage What is it exactly?",
        "section31_2": "As the name itself suggests, leverage trading allows traders to open positions that are much larger than the deposits they put in. ",
        "section31_3": "With leverage, you can easily experience how your purchasing power can be amplified and how to unlock your full trading potential. ",
        "section31_4": "However, please be aware that your losses will also be amplified by the leverage.",
        "section31_5": "Perks of Leverage Trading",
        "section31_6": "Magnify your potential profit",
        "section31_7": "Enjoy the freedom to go long or short",
        "section31_8": "Seize opportunities in market volatility",
        "section31_9": "Trade your favourite markets with leverage",
        "section31_10": "Magnify your potential profit",
        "section31_11": "Enjoy the freedom to go long or short",
        "section31_12": "Seize opportunities in market volatility",
        "section31_13": "rade your favourite markets with leverage",
        "section31_14": "How to Start",
        "section31_15": "1.Register an account",
        "section31_16": "With just your email address/mobile phone number and a login password",
        "section31_17": "2.Make a deposit",
        "section31_18": "Mitrade offers multiple depositing options:Wire transfer, Visa/ Mastercard, e-wallet, and TM/Ngan online banking^",
        "section31_19": "3.Wait & Trade",
        "section31_20": "With our fast deposit service, your funds will be on your account in no time! Make sure your international payment setting is on before making a deposit.",
        "section31_21": "4.Get Bonus as You Trade",
        "section31_22": "Enjoy trading rewards of up to $3,000*by participating in our bonus programmes.",
        "section31_23": "Sign up<",
        "section31_24": "^Not all methods are applicable in your country/region, see our platform for details",
        "section31_25": "Why Mitrade?",
        "section31_26": "ASIC regulated",
        "section31_27": "0 commission, low-cost trading",
        "section31_28": "Attractive leverage of up to 1:200 & tight spreads",
        "section31_29": "Exclusive market analysis from Trading Central",
        "section31_30": "Free hot tips and insights",
        "section31_31": "5/24 multilingual customer service support",
        "section31_32": "Trade on web or app",
        "section31_33": "Fast deposit & withdrawal",
        "section31_34": "Join Our Exclusive Reward Programmes!",
        "section31_35": "Get a free trial bonus of $50* (limited offer) when you open a live account with us.<br>Earn rewards as much as $3,000* when you trade.<br>The more you trade, the more you may earn!",
        "section31_36": "Sign up",
        "section31_37": "*Terms and Conditions apply. Check our website for details.",
        "footer_1": "On-The-Go Trading On Mobile App and Web",
        "footer_2": "<img src='img/btn-icon2.png' />Trade Now",
        "footer_3": "Privacy Policy | ",
        "footer_4": "Product Disclosure Statement | ",
        "footer_5": "Complaints Procedure | ",
        "footer_6": "Risk Disclosure Statement | ",
        "footer_7": "Client Agreement |",
        "footer_8": "Financial Services Guide | ",
        "footer_9": "Hedging Counterparties Policy",
        "footer_10": "Risk warning: Dealing with the over-the-counter derivatives is risky. It is not suitable for everyone and it can result in the loss of your entire capital. Please consider our PDS, FSG, Risk Disclosure Statement and Client Agreement before using our services and ensure that you understand the risks involved. You do not own or have any interest in the underlying assets.",
        "footer_11": "Mitrade does not issue advice, recommendations or opinion in relation to acquiring, holding or disposing of our products. The information on this website is general in nature and does not consider your personal objectives, financial circumstances or needs. Please seek for your own independent advice.",
        "footer_12": "All of our products are leveraged over-the-counter derivatives over global underlying assets. Mitrade provides execution only service, acting as principle at all times.",
        "footer_13": "This website is owned and operated by Mitrade Global Pty Ltd, headquartered at Melbourne, Australia and is licensed and regulated by Australian Securities and Investment Commission.",
        "footer_14": "The information on this site is not intended for residents of the United States, Canada, Japan, New Zealand or use by any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation.",
        "footer_15": "For certain jurisdictions, card processing service is provided by Mitrade Services Ltd (a company registered in England and Wales under number 11804044 with registered address at 27 Old Gloucester Street, London, WC1N 3AX, United Kingdom). Mitrade Services Ltd is wholly owned subsidiary of Mitrade Global Pty Ltd.",
        "footer_16": "<span class='glyphicon glyphicon-lock' aria-hidden='true'></span>&nbsp;Secured by SSL. © Mitrade Copyright, All rights reserved.| ABN 90 149 011 361 | AFSL 398528.",
        "footer_17": "",
        "footer_18": "",
        "placeholder_1": "The code you received via",
        "placeholder_2": "Please input password"
    },
    "vn": {
        "header_1": "Đăng ký",
        "header_2": "<img src='img/lang.png'/>Tiếng Việt",
        "header_3": "English",
        "header_4": "Tiếng Việt",
        "header_5": "ไทย",
        "header_6": "繁體中文",
        "section28_1": "Chiến lược giao dịch đòn bẩy hay nhất bạn sẽ cần!",
        "section28_2": "Thị trường tài chính thay đổi liên tục từng giây. Làm thế nào chúng ta có thể sử dụng đòn bẩy để gặt hái nhiều thành công trong thế giới tài chính?",
        "section28_3": "Và làm thế nào có thể tận dụng cơ chế đòn bẩy để làm chủ thị trường ?",
        "section28_4": "Số điện thoại",
        "section28_5": "+84",
        "section28_6": "Đài Loan <span>+886</span>",
        "section28_7": "Việt Nam <span>+84</span>",
        "section28_8": "Thái Lan <span>+66</span>",
        "section28_9": "Hàn Quố <span>+82</span>",
        "section28_10": "Philippines <span>+63</span>",
        "section28_11": "Malaysia <span>+60</span>",
        "section28_12": "Trung Quốc <span>+86</span>",
        "section28_13": "Úc <span>+61</span>",
        "section28_14": "Nhận mã",
        "section28_15": "Đăng ký an toàn",
        "section28_16": "Hoặc đăng nhập bằng",
        "section28_17": "Đã có tài khoản?<<a class='account-href' style='color:#0047BB;font-weight: 500;'>Đăng nhập</a>",
        "section31_1": "Giao dịch đòn bẩy- Chính xác nó là gì?",
        "section31_2": "Đúng như tên gọi của nó, đòn bẩy cho phép các nhà giao dịch mở một vị thế lớn hơn rất nhiều so với số tiền gửi mà họ cần đặt vào.",
        "section31_3": "Với đòn bẩy, nhà giao dịch có thể dễ dàng trải nghiệm sự Khuếch đại với sức mua của mình và từ đó mở khóa các tiềm năng giao dịch một cách đầy đủ nhất.",
        "section31_4": "Xin lưu ý, đòn bẩy cũng Khuếch đại tổn thất khi bạn thất bại.",
        "section31_5": "Lợi ích của giao dịch đòn bẩy",
        "section31_6": "Khuếch đại lợi nhuận tiềm năng của bạn",
        "section31_7": "Tận hưởng sự linh hoạt giúp bạn thoải mái trong việc mua và bán",
        "section31_8": "Nắm bắt cơ hội kịp thời trong biến động",
        "section31_9": "Thỏa sức giao dịch trên thị trường mà bạn yêu thích với đòn bẩy",
        "section31_10": "Khuếch đại lợi nhuận tiềm năng của bạn",
        "section31_11": "Tận hưởng sự linh hoạt giúp bạn thoải mái trong việc mua và bán",
        "section31_12": "Nắm bắt cơ hội kịp thời trong biến động",
        "section31_13": "Thỏa sức giao dịch trên thị trường mà bạn yêu thích với đòn bẩy",
        "section31_14": "Bắt đầu như thế nào?",
        "section31_15": "1.Đăng ký tài khoản thật",
        "section31_16": "Chỉ cần địa chỉ email/số điện thoại và tạo mật khẩu đăng nhập",
        "section31_17": "2.Gửi tiền",
        "section31_18": "Mitrade cung cấp các phương thức gửi tiền đa dạng: Chuyển khoản, Thẻ ATM, Thẻ Visa/Mastercard, ví điện tử, chuyển tiền qua Ngân Lượng ^",
        "section31_19": "3.Kiểm tra & Giao dịch",
        "section31_20": "Với dịch vụ gửi tiền nhanh chóng của chúng tôi, tiền của bạn sẽ vào tài khoản ngay lập tức!Từ đó bạn có thể bắt đầu giao dịch. Hãy đảm bảo rằng chức năng thanh toán quốc tế đã được bật trước khi bạn gửi tiền.",
        "section31_21": "4.Nhận thưởng khi giao dịch",
        "section31_22": "Tận hưởng tiền thưởng giao dịch lên đến $3.000* bằng cách tham gia các chương trình khuyến mãi của chúng tôi.",
        "section31_23": "Đăng ký ngay bây giờ",
        "section31_24": "^ Không phải toan bộ các phương thức đều được hỗ trợ cho khu vực / quốc gia của bạn, vui lòng xem thêm chi tiết tại nền tảng của chúng tôi",
        "section31_25": "Tại sao nên chọn Mitrade?",
        "section31_26": "Được quy định bởi ASIC",
        "section31_27": "0 phí hoa hồng, chi phí giao dịch thấp",
        "section31_28": "Tỉ lệ đòn bẩy lên tới 1:200 & Mức chênh lệch thấp",
        "section31_29": "Nhận phân tích thị trường độc quyền từ Trung Tâm Giao Dịch",
        "section31_30": "Nhận các mẹo và thông tin chi tiết hot miễn phí",
        "section31_31": "Dịch vụ chăm sóc khách hàng đa ngôn ngữ 24 giờ mỗi ngày, 5 ngày mỗi tuần",
        "section31_32": "Giao dịch trên cả web và ứng dụng",
        "section31_33": "Gửi & rút tiền nhanh chóng",
        "section31_34": "Tham gia chương trình thưởng độc quyền của chúng tôi!",
        "section31_35": "Nhận quỹ trải nghiệm 50$ *(Có thời hạn) khi bạn mở một tài khoản thật<br>Nhận thưởng lên đến 3.000$* khi bạn giao dịch<br>Giao dịch càng nhiều để nhận thưởng càng lớn!",
        "section31_36": "Đăng ký ngay bây giờ",
        "section31_37": "**Áp dụng các Điều khoản & Điều kiện. Xem chi tiết trên trang web của chúng tôi",
        "footer_1": "Giao dịch bất kì lúc nào với ứng dụng di động và web",
        "footer_2": "<img src='img/btn-icon2.png' />Giao dịch ngay",
        "footer_3": "Chính sách bảo mật | ",
        "footer_4": "Tuyên bố công bố sản phẩm | ",
        "footer_5": "Thủ tục khiếu nại | ",
        "footer_6": "Tuyên bố công bố rủi ro | ",
        "footer_7": "Thỏa thuận khách hàng |",
        "footer_8": "Hướng dẫn Dịch vụ Tài chính | ",
        "footer_9": "Chính sách đối tác phòng ngừa rủi ro",
        "footer_10": "Cảnh báo rủi ro: Sử dụng các công cụ phái sinh giao dịch trực tiếp là rủi ro. Nó không phù hợp cho tất cả mọi người và nó có thể dẫn đến việc mất toàn bộ vốn của bạn. Vui lòng xem xét PDS, FSG, Tuyên bố công bố rủi ro và Thỏa thuận khách hàng của chúng tôi trước khi sử dụng các dịch vụ của chúng tôi và đảm bảo rằng bạn hiểu các rủi ro liên quan. Bạn không sở hữu hoặc có bất kỳ quan tâm đến các tài sản cơ bản.",
        "footer_11": "Mitrade không đưa ra lời khuyên, khuyến nghị hoặc ý kiến ​​liên quan đến việc mua, giữ hoặc xử lý các sản phẩm của chúng tôi. Thông tin trên trang web này có bản chất chung chung và không xem xét các mục tiêu cá nhân, hoàn cảnh tài chính hoặc nhu cầu của bạn. Hãy tìm kiếm lời khuyên độc lập cho riêng bạn.",
        "footer_12": "Tất cả các sản phẩm của chúng tôi đều được sử dụng đòn bẩy, và là những hợp đồng được giao dịch trực tiếp giữa 2 bên mà không qua sàn giao dịch hay trung gian khác, giao dịch các tài sản cơ bản toàn cầu. Mitrade chỉ cung cấp dịch vụ thực hiện, hoạt động theo nguyên tắc vào mọi lúc.",
        "footer_13": "Trang web này được sở hữu và vận hành bởi Mitrade Global Pty Ltd, có trụ sở tại Melbourne, Úc và được cấp phép và quản lý bởi Ủy ban Chứng khoán và Đầu tư Úc.",
        "footer_14": "Thông tin trên trang này không dành cho cư dân của Hoa Kỳ, Canada, Nhật Bản, New Zealand hoặc bất kỳ người nào ở bất kỳ quốc gia hoặc khu vực tài phán nào mà việc phân phối hoặc sử dụng trái với luật pháp hoặc quy định của khu vực đó.",
        "footer_15": "Đối với một khu vực nhất định, dịch vụ xử lý thẻ được cung cấp bởi Mitrade Services Ltd (một công ty đã đăng ký tại Anh và xứ Wales theo số 11804044, có địa chỉ đăng ký tại 27 Old Gloucester Street, London, WC1N 3AX, Vương quốc Anh). Mitrade Services Ltd là công ty con thuộc sở hữu của Mitrade Global Pty Ltd.",
        "footer_16": "<span class='glyphicon glyphicon-lock' aria-hidden='true'></span>&nbsp;Được bảo mật bởi SSL. ©Mitrade Bản quyền, Tất cả các quyền. | ABN 90 149 011 361 | AFSL 398528.",
        "footer_17": "",
        "footer_18": "",
        "placeholder_1": "Mã xác nhận",
        "placeholder_2": "Mật khẩu mới"
    },
    "th": {
        "header_1": "เข้าสู่ระบบ",
        "header_2": "<img src='img/lang.png'/>ไทย",
        "header_3": "English",
        "header_4": "Tiếng Việt",
        "header_5": "ไทย",
        "header_6": "繁體中文",
        "section28_1": "กลยุทธ์การเทรดด้วยเลเวอเรจที่คุณต้องการ",
        "section28_2": "ตลาดเปลียนได้ภายในวินาที เราจะสามารถทำกำไรได้ในตลาดการเงินด้วยการใช้ประโยชน์จากเลเวอเรจอย่างไร?",
        "section28_3": "มีวิธีการหาจุดที่สมบูรณ์แบบของเลเวอเรจเพื่อย้ายตลาดหรือไม่?",
        "section28_4": "เปิดบัญชีเทรดจริง",
        "section28_5": "+66",
        "section28_6": "ไต้หวัน <span>+886</span>",
        "section28_7": "เวียดนาม <span>+84</span>",
        "section28_8": "ไทย <span>+66</span>",
        "section28_9": "เกาหลี <span>+82</span>",
        "section28_10": "ฟิลิปปินส์ <span>+63</span>",
        "section28_11": "มาเลเซีย <span>+60</span>",
        "section28_12": "จีน <span>+86</span>",
        "section28_13": "ออสเตรเลีย <span>+61</span>",
        "section28_14": "รับรหัส",
        "section28_15": "สร้างบัญชี",
        "section28_16": "หรือเข้าสู่ระบบผ่าน",
        "section28_17": "มีบัญชีเทรดแล้ว? <a class='account-href' style='color:#0047BB;font-weight: 500;'>ล็อกอิน</a>",
        "section31_1": "เทรดด้วยเลเวอเรจ มันคืออะไรกันแน่?",
        "section31_2": "ตามชื่อของมันให้เห็นว่า การเทรดด้วยเลเวอเรจจะทำให้เทรดเดอร์สามารถเปิดคำสั่งซื้อขายที่มีขนาดใหญ่กว่าเงินฝากไว้",
        "section31_3": "ด้วยเลเวอเรจ คุณสามารถสัมผัสได้อย่างง่ายดายว่ากำลังซื้อขายของคุณสามารถขยายถึงขนาดไหนและปลดล็อคศักยภาพการซื้อขายของคุณอย่างเต็มที่ได้อย่างไร",
        "section31_4": "อย่างไรก็ตาม โปรดทราบด้วยว่าการสูญเสียของคุณจะถูกขยายด้วยเลเวอเรจเช่นกัน",
        "section31_5": "ข้อดีในการเทรดด้วยเลเวอเรจ",
        "section31_6": "ขยายผลกำไรที่เป็นไปได้ของคุณ",
        "section31_7": "เปิดคำสั่งซื้อขายอย่างอิสระ",
        "section31_8": "คว้าโอกาสการลงทุนกับความผันผวนในตลาด",
        "section31_9": "เทรดตราสารที่คุณชื่นชอบด้วยเลเวอเรจ",
        "section31_10": "ขยายผลกำไรที่เป็นไปได้ของคุณ",
        "section31_11": "เปิดคำสั่งซื้อขายอย่างอิสระ",
        "section31_12": "คว้าโอกาสการลงทุนกับความผันผวนในตลาด",
        "section31_13": "เทรดตราสารที่คุณชื่นชอบด้วยเลเวอเรจ",
        "section31_14": "เริ่มต้นอย่างไร",
        "section31_15": "1.สมัครบัญชีเทรด",
        "section31_16": "ด้วยอีเมล / หมายเลขโทรศัพท์มือถือของคุณและรหัสผ่านเข้าสู่ระบบ",
        "section31_17": "2.ทำการฝากเงิน",
        "section31_18": "Mitrade นำเสนอตัวเลือกการฝากเงินหลากหลาย: การโอนเงินผ่านธนาคาร, Visa / Mastercard, <br>e-wallet, และธนาคารออนไลน์ TM / Ngan^",
        "section31_19": "3.รอ & เทรด",
        "section31_20": "ด้วยบริการฝากเงินที่รวดเร็วของเรา เงินของคุณจะเข้าสู่บัญชีเทรดภายในไม่กีนาที! โปรดตรวจสอบให้แน่ใจว่าการตั้งค่าการชำระเงินระหว่างประเทศของคุณได้ถูกเปิดก่อนทำการฝากเงิน",
        "section31_21": "4.รับโบนัสเมื่อทำการเทรด",
        "section31_22": "เพลิดเพลินกับโบนัสสูงถึง $3,000* โดยเข้าร่วมในโปรโมชั่นโบนัสของเรา",
        "section31_23": "สมัคร",
        "section31_24": "^ช่องทางการฝากเงินทั้งหมดอาจไม่มีให้บร <br> ิการในประเทศ/ภูมิภาคของคุณ <br>โปรดตรวจสอบรายละเอียดบนแพลตฟอร์มของเรา",
        "section31_25": "ทำไมเลือก Mitrade?",
        "section31_26": "กำกับดูแลโดย ASIC",
        "section31_27": "ม่มีค่าคอมมิชชั่น สเปรดต่ำ",
        "section31_28": "เลเวอเรจสูงสุดถึง 1:200 & สเปรดต่ำ",
        "section31_29": "การวิเคราะห์ตลาดเฉพาะตัวจากศูนย์การเทรด",
        "section31_30": "รับเคล็ดลับร้อนแรงและมุมมองเชิงลึกฟรี",
        "section31_31": "ฝ่ายบริการลูกค้าหลากหลายภาษาตลอด 5/24 ",
        "section31_32": "เทรดบนเว็บไซต์หรือแอพ",
        "section31_33": "ฝากถอนเงินรวดเร็ว",
        "section31_34": "เข้าร่วมกิจกรรมรับโบนัสเฉพาะตัวของเรา!",
        "section31_35": "เปิดบัญชีเทรดจริงรับโบนัสทดลองเทรด $50* <br>（ข้อเสนอจำกัด）<br>รับโบนัสมากสุดถึง $3,000* เมื่อทำการเทรด<br>ยิ่งเทรดมาก ยิ่งมีสิทธ์ได้รับโบนัสมากขึ้น!",
        "section31_36": "สมัคร",
        "section31_37": "*ตามข้อกำหนดและเงื่อนไข <br>ตรวจสอบรายละเอียดบนเว็บไซต์เรา",
        "footer_1": "พร้อมทำการเทรดบนแอพมือถือและเว็บทุกที่ทุกเวลา",
        "footer_2": "<img src='img/btn-icon2.png' />เทรดเดี๋ยวนี้",
        "footer_3": "นโบบายความเป็นส่วนตัว | ",
        "footer_4": "เอกสารเปิดเผยข้อมูลผลิตภัณฑ์ | ",
        "footer_5": "ขั้นตอนการร้องเรียน | ",
        "footer_6": "เอกสารเปิดเผยข้อมูลความเสี่ยง | ",
        "footer_7": "ข้อตกลงของลูกค้า |",
        "footer_8": "คู่มือแนะนำให้บริการทางการเงิน | ",
        "footer_9": "นโยบายการประกันความเสี่ยงจากคู่สัญญาในการทำธุรกรรม",
        "footer_10": "คำเตือนเกี่ยวกับความเสี่ยง: ฟอเร็กซ์ สกุลเงินดิจิตอล และดัชนีเป็นตราสารที่ใช้เลเวอเรจในการซื้อขาย ซึ่งอาจส่งผลให้ท่านสูญเสียเงินลงทุนขั้นต้น แอพพลิเคชั่นเทรด Mitrade อาจไม่เหมาะสมสำหรับนักลงทุนทุกท่าน เพื่อเข้าใจถึงความเสี่ยงที่อาจเกิดขึ้นท่านควรพิจารณาเอกสารข้อมูลเปิดเผยเกี่ยวกับผลิตภัณฑ์ (PDS) คู่มือคำแนะนำให้บริการทางการเงิน (FSG) เอกสารเปิดเผยข้อมูลความเสี่ยง(Risk Disclosure Statement) และข้อตกลงของลูกค้า (Client Agreement) ก่อนที่จะใช้บริการของเรา โปรดทราบว่าท่านจะไม่ได้เป็นเจ้าของสินทรัพย์ และจะไม่ได้รับดอกเบี้ยใด ๆ ภายใต้การลงทุนทรัพย์สินนี้",
        "footer_11": "Mitrade ไม่ได้ให้คำปรึกษาหรือข้อแนะนำที่เกี่ยวข้องกับการได้รับ การถือครอง หรือการละทิ้งตราสารต่าง ๆ",
        "footer_12": "ตราสารของเราเป็นแบบการซื้อขายโดยตรง โดย Mitrade จะดำเนินการส่งคำสั่งซื้อขายอย่างเดียวเท่านั้น",
        "footer_13": "Mitrade ไม่ได้ให้บริการซื้อหรือขายสกุลเงินดิจิตอลใด ๆ และไม่ได้ให้บริการแลกเปลี่ยนสกุลเงินดิจิตอล",
        "footer_14": "เว็บไซด์นี้ถูกครอบครองและจัดทำโดย Mitrade Global Pty Ltd ABN 90 149 011 361, AFSL 398528. ใบอนุญาต AFSL ให้สิทธิ Mitrade ในการให้บริการทางด้านการเงินในประเทศออสเตรเลีย ท่านสามารถติดต่อ Mitrade ได้ผ่านทางอีเมล์ cs@mitrade.com",
        "footer_15": "ข้อมูลในเว็บไซต์นี้ไม่ได้มีไว้สำหรับผู้ที่อาศัยอยู่ในสหรัฐอเมริกา แคนาดา ญี่ปุ่น นิวซีแลนด์ หรือใช้งานโดยบุคคลใด ๆ ในประเทศหรือเขตอำนาจศาลที่การใช้งานดังกล่าวอาจขัดต่อกฎหมายหรือระเบียบข้อบังคับของท้องถิ่น",
        "footer_16": "<span class='glyphicon glyphicon-lock'></span>&nbsp;Secured by SSL. © Mitrade Copyright, All rights reserved.",
        "footer_17": "โปรดทราบว่าภาษาอังกฤษเป็นภาษาหลักที่ใช้สำหรับบริการของเราและเป็นภาษาที่มีประสิทธิภาพตามกฎหมายในเอกสารสัญญาทั้งหมดของเรา เวอร์ชั่นภาษาไทยใช้สำหรับการอ้างอิงเท่านั้นหากการแปลนั้นไม่สอดคล้องกับภาษาอังกฤษ โปรดตามภาษาอังกฤษ",
        "footer_18": "สำหรับพื้นที่เฉพาะ การประมวลผลบัตรให้บริการโดย Mitrade Services Ltd (บริษัท ที่จดทะเบียนในอังกฤษและเวลส์ภายใต้หมายเลข 11804044 จดทะเบียนที่ 27 Old Gloucester Street, London, WC1N 3AX, สหราชอาณาจักร) Mitrade Services Ltd เป็น บริษัท ในเครือของ Mitrade Global Pty Ltd.",
        "placeholder_1": "รหัสที่คุณรับผ่าน",
        "placeholder_2": "กรุณากรอกรหัสผ่าน"
    }
};